### ISSUE TITLE
Nonstatic method called in static context

### ISSUE THREAD

**Issue by ghost** [centertap/TikaAllTheFiles#3]
At `src/Core.php`  line 493 the MediaWiki core method `flattenArrayReal()` is called as if it were a static method.  But it has not been a static method for the last ten years, according to the git log of MediaWiki.   This predates the apparent age of the TikaAllTheFiles project by six years or so, which is puzzling.

It does not help that the TikaAllThefiles git history is one monolithic commit.  But my guess is that the code involved is a cut-and-paste from code in MediaWiki, and an old version of of MediaWiki, and really is just broken with any remotely-recent version of MediaWiki.

In any case, this results, as expected, in a runtime error when the code path hits encounters a `$this` reference, which happens.

```
      $formatted[ $visibility ][] = [
          'id' => $mapped->id(),
          'name' => $mapped->name(),
          'value' => FormatMetadata::flattenArrayReal( $mapped->values(),
                                                       /*type=*/'ul',
                                                       /*noHtml=*/false ),
```

**Comment by mdoggydog** [comment]
This is fixed now in 1.0.2. 

(Somehow my "Watch" setting on this repo was mis-set so I never received a notification for this issue!  I had no idea anyone else even looked at this extension.)

> But it has not been a static method for the last ten years, according to the git log of MediaWiki. This predates the apparent age of the TikaAllTheFiles project by six years or so, which is puzzling.
>
> It does not help that the TikaAllThefiles git history is one monolithic commit. But my guess is that the code involved is a cut-and-paste from code in MediaWiki, and an old version of of MediaWiki, and really is just broken with any remotely-recent version of MediaWiki.

Yeah, it's a mystery to me, too.  Maybe I found this usage in some other extension; maybe I just didn't notice it wasn't static?  Either way, TikaAllTheFiles was originally developed under MW 1.35, and it did work at the time.  I think PHP 7.4 was simply much more permissive....
